version: '2'
services:
    cra-app:
        image: cra
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://cra-mariadb:3306/cra
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://cra-elasticsearch:9200
        ports:
            - 8080:8080
    cra-mariadb:
        extends:
            file: mariadb.yml
            service: cra-mariadb
    cra-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cra-elasticsearch
